src/RM/ProductoBundle/Entity/NumPromociones.php
<?php

namespace RM\ProductoBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use RM\ComunicacionBundle\Entity\InstanciaComunicacion;
use RM\PlantillaBundle\Entity\GrupoSlots;
use RM\CategoriaBundle\Entity\Categoria;

/**
 * NumPromociones
 *
 * @ORM\Table(name="num_promociones")
 * @ORM\Entity(repositoryClass="RM\ProductoBundle\Entity\NumPromocionesRepository")
 */
class NumPromociones
{

    public function __construct()
    {
        $this->promociones = new ArrayCollection();
    }


    /**
     * @var integer
     *
     * @ORM\Column(name="num_segmentadas", type="integer", nullable=true)
     * @Assert\GreaterThanOrEqual( value = 0)
     */
    private $numSegmentadas;

    /**
     * @var integer
     *
     * @ORM\Column(name="num_genericas", type="integer", nullable=true)
     * @Assert\GreaterThanOrEqual(value = 0)
     */
    private $numGenericas;

    /**
     * @var int
     *
     * @ORM\Column(name="estado", type="smallint", nullable=true, options={"default" = 1})
     */
    private $estado = 1;

    /**
     * @var integer
     *
     * @ORM\Column(name="id_num_pro", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idNumPro;

    /**
     * @var \RM\ComunicacionBundle\Entity\InstanciaComunicacion
     *
     * @ORM\ManyToOne(targetEntity="RM\ComunicacionBundle\Entity\InstanciaComunicacion", inversedBy="numPromociones")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_instancia", referencedColumnName="id_instancia")
     * })
     * @Assert\NotBlank()
     */
    private $idInstancia;

    /**
     * @var \RM\PlantillaBundle\Entity\GrupoSlots
     *
     * @ORM\ManyToOne(targetEntity="RM\PlantillaBundle\Entity\GrupoSlots")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_grupo", referencedColumnName="id_grupo")
     * })
     * @Assert\NotBlank()
     */
    private $idGrupo;

    /**
     * @var \RM\CategoriaBundle\Entity\Categoria
     *
     * @ORM\ManyToOne(targetEntity="RM\CategoriaBundle\Entity\Categoria")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_categoria", referencedColumnName="id_categoria")
     * })
     */
    private $idCategoria;

    /**
     * @var \RM\ProductoBundle\Entity\Promocion
     * @ORM\OneToMany(targetEntity="RM\ProductoBundle\Entity\Promocion", mappedBy="numPromocion", indexBy="idPromocion")
     *
     */
    private $promociones;


    private $nombre = '';

    public function getNombre()
    {
        if($this->idCategoria instanceof Categoria) {
            $this->nombre = $this->idCategoria->getNombre();
        }

        return $this->nombre;
    }





    /**
     * Set numSegmentadas
     *
     * @param integer $numSegmentadas
     * @return NumPromociones
     */
    public function setNumSegmentadas($numSegmentadas)
    {
        $this->numSegmentadas = $numSegmentadas;
    
        return $this;
    }

    /**
     * Get numSegmentadas
     *
     * @return integer 
     */
    public function getNumSegmentadas()
    {
        return $this->numSegmentadas;
    }

    /**
     * Set numGenericas
     *
     * @param integer $numGenericas
     * @return NumPromociones
     */
    public function setNumGenericas($numGenericas)
    {
        $this->numGenericas = $numGenericas;
    
        return $this;
    }

    /**
     * Get numGenericas
     *
     * @return integer 
     */
    public function getNumGenericas()
    {
        return $this->numGenericas;
    }

    /**
     * Set estado
     *
     * @param int $estado
     * @return NumPromociones
     */
    public function setEstado($estado)
    {
        $this->estado = $estado;
    
        return $this;
    }

    /**
     * Get estado
     *
     * @return int
     */
    public function getEstado()
    {
        return $this->estado;
    }

    /**
     * Get idNumPro
     *
     * @return integer 
     */
    public function getIdNumPro()
    {
        return $this->idNumPro;
    }

    /**
     * Set idInstancia
     *
     * @param InstanciaComunicacion $idInstancia
     * @return NumPromociones
     */
    public function setIdInstancia(InstanciaComunicacion $idInstancia = null)
    {
        $this->idInstancia = $idInstancia;
    
        return $this;
    }

    /**
     * Get idInstancia
     *
     * @return \RM\ComunicacionBundle\Entity\InstanciaComunicacion 
     */
    public function getIdInstancia()
    {
        return $this->idInstancia;
    }

    /**
     * Set idGrupo
     *
     * @param GrupoSlots $idGrupo
     * @return NumPromociones
     */
    public function setIdGrupo(GrupoSlots $idGrupo = null)
    {
        $this->idGrupo = $idGrupo;
    
        return $this;
    }

    /**
     * Get idGrupo
     *
     * @return GrupoSlots
     */
    public function getIdGrupo()
    {
        return $this->idGrupo;
    }

    /**
     * Set idCategoria
     *
     * @param Categoria $idCategoria
     * @return NumPromociones
     */
    public function setIdCategoria(Categoria $idCategoria = null)
    {
        $this->idCategoria = $idCategoria;
    
        return $this;
    }

    /**
     * Get idCategoria
     *
     * @return Categoria
     */
    public function getIdCategoria()
    {
        return $this->idCategoria;
    }

    /**
     * Add promociones
     *
     * @param Promocion $promociones
     * @return NumPromociones
     */
    public function addPromocion(Promocion $promociones)
    {
        $promociones->setNumPromocion($this);

        $this->promociones->add($promociones);
    
        return $this;
    }

    /**
     * Remove promociones
     *
     * @param \RM\ProductoBundle\Entity\Promocion $promociones
     */
    public function removePromocion(Promocion $promociones)
    {
        $this->promociones->removeElement($promociones);
    }

    /**
     * Get promociones
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPromociones()
    {
        return $this->promociones->filter(function (Promocion $promocion){
                return $promocion->getEstado() > -1;
            });
    }

    /**
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPromocionesSegmentadas(){

      return $this->promociones->filter(function(Promocion $promocion){
        return $promocion->getTipo() == Promocion::TIPO_SEGMENTADA
              && $promocion->getEstado() > -1;
      });

    }

    /**
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPromocionesGenericas(){

      return $this->promociones->filter(function(Promocion $promocion){
        return $promocion->getTipo() ==  Promocion::TIPO_GENERICA
            && $promocion->getEstado() > -1;
      });

    }


    /**
     * @return bool
     */
    public function isSegementadasCompletas()
    {
        return $this->getPromocionesSegmentadas()->count() >= $this->numSegmentadas;
    }

    /**
     * @return bool
     */
    public function isGenericasCompletas()
    {
        return $this->getPromocionesGenericas()->count() >= $this->numGenericas;
    }

    /**
     * @return int
     */
    public function getTotalPromociones()
    {
        return
            (int) $this->numSegmentadas + $this->numGenericas;
    }

    /**
     * @return int
     */
    public function getTotalPromocionesRealizadas()
    {
        return
            (int) $this->getPromocionesGenericas()->count() + $this->getPromocionesSegmentadas()->count();
    }

    /**
     * @return bool
     */
    public function isNingunaPromocionPendiente()
    {
        /** @var Promocion $promocion */
        foreach ($this->getPromocionesSegmentadas() as $promocion) {
            if (Promocion::PENDIENTE === $promocion->getAceptada()) {
                return false;
            }
        }

        return true;
    }

    /**
     * @return int
     */
    public function getTotalPromocionesAceptadas()
    {
        return $this->getPromocionesByEstado(Promocion::ACEPTADA);
    }

    /**
     * @return int
     */
    public function getTotalPromocionesPendientes()
    {
        return $this->getPromocionesByEstado(Promocion::PENDIENTE);
    }

    /**
     * @return int
     */
    public function getTotalPromocionesRechazadas()
    {
        return $this->getPromocionesByEstado(Promocion::RECHAZADA);
    }

    /**
     * @param $estado
     *
     * @return int
     */
    public function getPromocionesByEstado($estado)
    {

        $promociones = $this
            ->getPromocionesSegmentadas();

        $promociones = $promociones->filter(function(Promocion $promocion) use ($estado) {
                return $estado === $promocion->getAceptada();
            });

        return $promociones->count();
    }
}

src/RM/ProductoBundle/Form/PromocionType.php
<?php

namespace RM\ProductoBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PromocionType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('descripcion', 'text', ['required' => false])
            ->add('impConsumidor', 'number', ['required' => false])
            ->add('impDistribuidor', 'number', ['required' => false])
            ->add('impFijo', 'number', ['required' => false])
            ->add('condiciones', 'text', ['required' => false])
            ->add('fidelizacion', 'text', ['required' => false])
            ->add('codigo', 'text')
        ;
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => 'RM\ProductoBundle\Entity\Promocion'
        ]);
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'rm_productobundle_promocion';
    }
}

src/RM/ProductoBundle/Resources/views/Promocion/base_promocion.html.twig
{% extends ':campaign:base_campaign.html.twig' %}


{% block stylesheets %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('js/datepicker/jquery-datepicker.js') }}"></script>

    <script type="text/javascript">
        $(document).ready(function(){

            $(document).on('focus', '.datepicker', function(){
                $(this).datepicker({ dateFormat: "dd/mm/yy" });
            })

        });
    </script>

{% endblock stylesheets %}

{% block title %}{{ "promocion" |trans|title}}{% endblock %}

{% block pagetitle %}
    <h5>{{ promocion.getNumPromocion.idCategoria.nombre|default('creatividad'|trans) }}</h5>
    <h1>{{ "promocion" |trans|title}}</h1>
{% endblock pagetitle %}

{% block migas %}
    <li>
        <a href="{{ path('campaign_campanyas') }}"><span class="iconfa-home"></span></a>
        <span class="separator"></span>
    </li>
    <li>
        <a href="{{ path('campaign_campanyas') }}">
            {{ "menu.campaign.campanas" |trans|title }}
        </a>
        <span class="separator"></span></li>
    <li>
        <a href="{{ path('campaign_ficha', {'id_instancia': promocion.getNumPromocion.getIdInstancia.idInstancia }) }}">
            #{{ "%07d"|format(promocion.getNumPromocion.getIdInstancia.idInstancia) }}
        </a>
        <span class="separator"></span>
    </li>
    <li>{{ promocion.getNumPromocion.idCategoria.nombre|default('') }} <span class="separator"></span></li>
    <li>{{ "promocion" |trans|title}}</li>
{% endblock migas %}

{% block id %}ajax{% endblock id %}

{% block body %}
    <h4 class="widgettitle">{% block widgettitle %}{% endblock widgettitle %}</h4>
    <div class="mediamgr_head">
        <div class="container">
            {% block content %}{% endblock content %}
        </div>
    </div>
{% endblock body %}


src/RM/ProductoBundle/Resources/views/Promocion/form_generica.html.twig
{% extends '@RMProducto/Promocion/base_promocion.html.twig' %}

{% set objInstancia = promocion.numPromocion.idInstancia %}

{% block widgettitle %}{{ "genericas" |trans|title }}{% endblock widgettitle %}

{% block content %}
    {{ form_start(form, {'attr': {'class': 'form-horizontal' }}) }}
    <div id="content">
        <div class="row-fluid">
            <div class="span6">
                <fieldset>
                    <legend>{{ "promocion" |trans|title }} - {{ promocion.numPromocion.idCategoria.nombre }}</legend>
                        <div class="control-group {% if not form.marca.vars.valid %}error{% endif %}">
                            {{ form_label(form.marca, null, {'label_attr': {'class': 'control-label'} }) }}
                            <div class="controls">
                                {{ form_widget(form.marca, {'attr': {'class' : 'change span8' }}) }}
                                <span class="help-inline">
                                    {% for error in form.marca.vars.errors %}
                                        {{ error.message }} <br/>
                                    {% endfor %}
                                </span>
                            </div>
                        </div>

                        <div class="control-group">
                            {{ form_label(form.idProducto, null,  {'label_attr': {'class': 'control-label'} }) }}
                            <div class="controls">
                                {{ form_widget(form.idProducto, {'attr': {'class' : 'span8' }}) }}
                            </div>
                        </div>

                        <div class="control-group {% if not form.idTipoPromocion.vars.valid %}error{% endif %}">
                            {{ form_label(form.idTipoPromocion, null,  {'label_attr': {'class': 'control-label'} }) }}
                            <div class="controls">
                                {{ form_widget(form.idTipoPromocion, {'attr': {'class' : 'span8' }}) }}
                                <span class="help-inline">
                                    {% for error in form.idTipoPromocion.vars.errors %}
                                        {{ error.message }} <br/>
                                    {% endfor %}
                                </span>
                            </div>
                        </div>

                    <div class="control-group {% if not form.fechaCaducidad.vars.valid %}error{% endif %}">
                        {{ form_label(form.fechaCaducidad, null, {'label_attr': {'class': 'control-label'} }) }}
                        <div class="controls">
                            {{ form_widget(form.fechaCaducidad, {'attr': {'class': 'datepicker span8'}}  ) }}
                            <span class="help-inline">
                                {% for error in form.fechaCaducidad.vars.errors %}
                                    {{ error.message }}
                                {% endfor %}
                            </span>
                        </div>
                    </div>

                </fieldset>
            </div>
            <div class="span6">
                {% include '@RMProducto/Promocion/form_promocion_parte_comun.html.twig' with {'form': form} %}
            </div>
        </div>
        <div class="row-fluid">
                <div class="form-actions">
                    {{ form_widget(form.submit, {'attr': {'class': 'btn btn-primary' }}) }}
                </div>
            </div>
    </div>

    {{ form_widget(form.filtro, {
    'attr': {
    'class': 'filtro',
    'data-promocion': promocion.idPromocion is not null ? promocion.idPromocion : -1
    }
    }) }}

    {{ form_end(form) }}

    <script type="text/javascript">
        $(document).on('ready', function () {

            $(document).on('click', '.voucher_generator', genereateVoucher)

            function addCondicionSegmentoPadreGenericas(elem) {
                if (typeof elem === 'undefined') {
                    return false;
                }

                var filtro = '{"$and": [{"ls": {"$in": [{{ objInstancia.idSegmentoComunicacion.idSegmento.idSegmento }}] } } ] }';
                var value = {
                    filtroCompleto: filtro
                };

                elem.value = JSON.stringify(value);
            }

            $('.filtro').each(function () {
                addCondicionSegmentoPadreGenericas(this);
            });

            function genereateVoucher(event){
                var e = event||window.event;
                e.preventDefault();
                var codigo = document.getElementById('{{ form.codigo.vars.id }}');

                $.get('{{ path('rm_producto.promocion.get_unique_voucher') }}', function(data){
                    codigo.value = data.voucher;
                });
            }


            $(document).on('change', '.change', function (event) {
                var e = event || window.event;
                e.preventDefault();

                var $form = $(this).closest('form');
                var form_data = $form.serializeArray().reduce(function (obj, item) {
                    obj[item.name] = item.value;
                    return obj;
                }, {});
                delete form_data['{{ form._token.vars.full_name }}'];

                $.ajax({
                    method: $form.attr('method'),
                    url: $form.attr('action'),
                    data: form_data,
                    success: function (response) {
                        $form.find('#content').html($(response).find('#content'));
                    }
                });

            });
        });
    </script>

{% endblock content %}

src/RM/ProductoBundle/Resources/views/Promocion/list_creatividad_genericas.html.twig
{% if num_promocion.numGenericas > 0 %}
    {% set genericas_restantes = num_promocion.numGenericas - num_promocion.promocionesGenericas.count %}

    <h4 class="widgettitle">{{ "genericas" |trans|title }}</h4>
    <table class="table table-bordered">
        <colgroup>
            <col class="con0">
            <col class="con1">
            <col class="con0">
            <col class="con1">
            <col class="con0">
            <col class="con1">
        </colgroup>
        <thead>
        <tr>
            <th width="30%">{{ "descripcion" |trans|title }}</th>
            <th width="15%">{{ "creatividad" |trans|title }}</th>
            <th width="10%">{{ "simulado" |trans|title }}</th>
            <th>{{ "controles" |trans|title }}</th>
        </tr>
        </thead>

        <tbody>
        {% for generica in num_promocion.promocionesGenericas %}
            <tr data-id-promocion="{{ generica.idPromocion }}">
                <td class="center-all">{{ generica.descripcion }}</td>
                <td class="center-all">

                    {% if generica.creatividad is not null %}
                        {% set url_creatividad = ruta_imagen_creatividad(generica.creatividad.imagen) %}
                        <img src="{{ asset(url_creatividad) }}" width="40%"/>
                    {% endif %}
                </td>
                <td class="center-all">{{ generica.simulado }}</td>
                <td class="center-all">
                    <a href="{{ path('rm_producto.promocion.creatividad_edit', {'id': generica.idPromocion}) }}"
                       class="btn btn-warning"><i class="iconfa iconfa-edit"></i></a>
                    <!--<a href="#" class="btn btn-danger"><i class="iconfa iconfa-trash"></i></a>-->
                </td>
            </tr>
        {% endfor %}

            <tr>
                <td colspan="5" class="center-all">
                    <div class="well well-small">
                       <div>
                           <a class="btn btn-success"
                              href="{{ path('rm_producto.promocion.creatividad_generica_new', {'idNumPromocion': num_promocion.idNumPro}) }}">
                               <i class="iconfa iconfa-plus"></i>
                           </a>
                       </div>
                        {% if genericas_restantes > 0 %}
                        <p class="text-info">
                            <strong>{{ "informacion.creatividades.restantes" |transchoice(genericas_restantes) }}</strong>
                        </p>
                        {% endif %}
                    </div>

                </td>
            </tr>

        </tbody>
    </table>
{% endif %}

src/RM/ProductoBundle/Resources/views/Promocion/list_creatividad_segmentadas.html.twig
{% if num_promocion.numSegmentadas > 0 %}
    {% set segmentadas_restantes = num_promocion.numSegmentadas - num_promocion.promocionesSegmentadas.count %}

    <h4 class="widgettitle">{{ "segmentadas" |trans|title }}</h4>
    <table class="table table-responsive table-bordered">
        <colgroup>
            <col class="con0">
            <col class="con1">
            <col class="con0">
            <col class="con1">
            <col class="con0">
            <col class="con1">
        </colgroup>
        <thead>
        <tr>
            <th width="30%">{{ "descripcion" |trans|title }}</th>
            <th width="15%">{{ "creatividad" |trans|title }}</th>
            <th width="10%">{{ "simulado" |trans|title }}</th>
            <th width="35%">{{ "segmentos" |trans|title }}</th>
            <th width="10%">{{ "controles" |trans|title }}</th>
        </tr>
        </thead>
        <tbody>
        {% for segmentada in num_promocion.promocionesSegmentadas %}
            <tr data-id-promocion="{{ segmentada.idPromocion }}">
                <td class="center-all">{{ segmentada.descripcion }}</td>
                <td class="center-all">
                    {% if segmentada.creatividad is not null %}
                        {% set url_creatividad = ruta_imagen_creatividad(segmentada.creatividad.imagen) %}
                        <img src="{{ asset(url_creatividad) }}" width="40%"/>
                    {% endif %}
                </td>
                <td class="center-all">{{ segmentada.simulado }}</td>
                <td class="center-all">{{ segmentada.nombreFiltro }}</td>
                <td class="center-all">
                    <a href="{{ path('rm_producto.promocion.creatividad_edit', {'id': segmentada.idPromocion}) }}"
                       class="btn btn-warning">
                        <i class="iconfa iconfa-edit"></i></a>
                    <!--<a href="#" class="btn btn-danger"><i class="iconfa iconfa-trash"></i></a>-->
                </td>
            </tr>
        {% endfor %}
            <tr>
                <td colspan="6" class="center-all">
                    <div class="well well-small">
                        <div>
                            <a class="btn btn-success"
                               href="{{ path('rm_producto.promocion.creatividad_segmentada_new', {'idNumPromocion': num_promocion.idNumPro}) }}">
                                <i class="iconfa iconfa-plus"></i>
                            </a>
                        </div>
                        {% if segmentadas_restantes > 0 %}
                        <p class="text-info">
                            <strong>{{ "informacion.creatividades.restantes" |transchoice(segmentadas_restantes) }}</strong>
                        </p>
                        {% endif %}
                    </div>

                </td>
            </tr>

        </tbody>
    </table>

{% endif %}

src/RM/ProductoBundle/Resources/views/Promocion/list_genericas.html.twig
{% if num_promocion.numGenericas > 0 %}
    {% set genericas_restantes = num_promocion.numGenericas - num_promocion.promocionesGenericas.count %}

    <h4 class="widgettitle">{{ "genericas" |trans|title }}</h4>
    <table class="table table-bordered">
        <colgroup>
            <col class="con0">
            <col class="con1">
            <col class="con0">
            <col class="con1">
            <col class="con0">
            <col class="con1">
        </colgroup>
        <thead>
        <tr>
            <th width="25%">{{ "producto" |trans|title }}</th>
            <th width="15%">{{ "tipo.promocion" |trans|title }}</th>
            <th>{{ "controles" |trans|title }}</th>
        </tr>
        </thead>

        <tbody>
        {% for generica in num_promocion.promocionesGenericas %}
            <tr data-id-promocion="{{ generica.idPromocion }}">
                <td class="center-all">{{ generica.idProducto.nombre }}</td>
                <td class="center-all">{{ generica.idTipoPromocion.nombre }}</td>
                <td class="center-all">
                    <a href="{{ path('rm_producto.promocion.generica_edit', {'id': generica.idPromocion, 'returnUrl': returnUrl|default('') }) }}"
                       class="btn btn-warning"><i class="iconfa iconfa-edit"></i></a>
                    <!--<a href="#" class="btn btn-danger"><i class="iconfa iconfa-trash"></i></a>-->
                </td>
            </tr>
        {% endfor %}

            <tr>
                <td colspan="5" class="center-all">
                    <div class="well well-small">
                        <div>
                            <a class="btn btn-success"
                               href="{{ path('rm_producto.promocion.generica_new', {'idNumPromocion': num_promocion.idNumPro, 'returnUrl': returnUrl|default('')}) }}">
                                <i class="iconfa iconfa-plus iconfa-align-center"></i>
                            </a>
                        </div>
                        {% if genericas_restantes > 0 %}
                            <p class="text-info">
                                <strong>{{ "informacion.promociones.restantes" |transchoice(genericas_restantes) }}</strong>
                            </p>
                        {% endif %}
                    </div>
                </td>
            </tr>

        </tbody>
    </table>
{% endif %}

src/RM/ProductoBundle/Resources/views/Promocion/list_segmentadas.html.twig
{% if num_promocion.numSegmentadas > 0 %}
    {% set segmentadas_restantes = num_promocion.numSegmentadas - num_promocion.promocionesSegmentadas.count %}

    {% if returnUrl is not defined %}
        {% set returnUrl = '' %}
    {% endif %}

    <h4 class="widgettitle">{{ "segmentadas" |trans|title }}</h4>
    <table class="table table-responsive table-bordered">
        <colgroup>
            <col class="con0">
            <col class="con1">
            <col class="con0">
            <col class="con1">
            <col class="con0">
            <col class="con1">
        </colgroup>
        <thead>
        <tr>
            <th width="25%">{{ "producto" |trans|title }}</th>
            <th width="15%">{{ "tipo.promocion" |trans|title }}</th>
            <th width="5%">{{ "poblacion" |trans|title }}</th>
            <th width="5%">{{ "minimo" |trans|title }}</th>
            <th width="40%">{{ "segmentos" |trans|title }}</th>
            <th width="10%">{{ "controles" |trans|title }}</th>
        </tr>
        </thead>
        <tbody>
        {% for segmentada in num_promocion.promocionesSegmentadas %}
            <tr data-id-promocion="{{ segmentada.idPromocion }}">
                <td class="center-all">{{ segmentada.idProducto.nombre }}</td>
                <td class="center-all">{{ segmentada.idTipoPromocion.nombre }}</td>
                <td class="center-all">{{ segmentada.poblacion|localizednumber }}</td>
                <td class="center-all">{{ segmentada.minimo|localizednumber}}</td>
                <td class="center-all">{{ segmentada.nombreFiltro }}</td>
                <td class="center-all">
                    <a href="{{ path('rm_producto.promocion.segmentada_edit', {'id': segmentada.idPromocion, 'returnUrl': returnUrl}) }}"
                       class="btn btn-warning">
                        <i class="iconfa iconfa-edit"></i></a>
                    <!--<a href="#" class="btn btn-danger"><i class="iconfa iconfa-trash"></i></a>-->
                </td>
            </tr>
        {% endfor %}

            <tr>
                <td colspan="6" class="center-all">
                    <div class="well well-small">
                        <div>
                            <a class="btn btn-success"
                               href="{{ path('rm_producto.promocion.segmentada_new', {'idNumPromocion': num_promocion.idNumPro, 'returnUrl': returnUrl|default('')})  }}">
                                <i class="iconfa iconfa-plus iconfa-align-center"></i>
                            </a>
                        </div>
                        {% if segmentadas_restantes > 0 %}
                            <p class="text-info">
                                <strong>{{ 'informacion.promociones.restantes'|transchoice(segmentadas_restantes) }}</strong>
                            </p>
                        {% endif %}

                    </div>

                </td>
            </tr>

        </tbody>
    </table>

{% endif %}